###
GET http://localhost:9000/oauth2/.well-known/jwks.json

###
GET http://localhost:9000/api/hello
Authorization: Bearer eyJraWQiOiI5ZmQxNjhhNy1jY2ZhLTRlZGUtYWFmMS1kZmQ3OTQ4ZTMyNGQiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTYyODQzNzY1NCwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjI4NDU1NjU0LCJpYXQiOjE2Mjg0Mzc2NTQsImp0aSI6IjVlYjQ0YTQ5LTM3YjItNDMxNy05ODNiLTA1MWExZDE0YmJjNyJ9.FFEmykhREAXdk5WdPq3nOnf0jBzXyULMQF6brnu6wtjzsRDVofK1w05PY1RJWIayrSYrY4klnUZtEmMpuE95v-CzG87YGT2r2Y0sEvwfETgx34iff_uRgQpU4LvMqtGNP6c_caThCDKGX9nVXvBeBy9_RdqEjhqFeY1nPAHUvz-wwIt-_By0jp7gf__5cVEHbsLcdSnLJGkD_9AqYDY967lf41MgaarijI5iHWZ_471mNMQOjukh131sdKcB11P4n0JtmjVuTX_CJaaGPN-587wag5DMxGXb8mMBaMluLNRoEVuPGbe04BlYQKKgCvR9Qx25qmTsdTVAxuz-BTp3mQ

###
POST http://localhost:9000/oauth2/token?grant_type=client_credentials
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

###
POST http://localhost:9000/oauth2/introspect
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

token=eyJraWQiOiI5ZmQxNjhhNy1jY2ZhLTRlZGUtYWFmMS1kZmQ3OTQ4ZTMyNGQiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTYyODQzNzY1NCwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjI4NDU1NjU0LCJpYXQiOjE2Mjg0Mzc2NTQsImp0aSI6IjVlYjQ0YTQ5LTM3YjItNDMxNy05ODNiLTA1MWExZDE0YmJjNyJ9.FFEmykhREAXdk5WdPq3nOnf0jBzXyULMQF6brnu6wtjzsRDVofK1w05PY1RJWIayrSYrY4klnUZtEmMpuE95v-CzG87YGT2r2Y0sEvwfETgx34iff_uRgQpU4LvMqtGNP6c_caThCDKGX9nVXvBeBy9_RdqEjhqFeY1nPAHUvz-wwIt-_By0jp7gf__5cVEHbsLcdSnLJGkD_9AqYDY967lf41MgaarijI5iHWZ_471mNMQOjukh131sdKcB11P4n0JtmjVuTX_CJaaGPN-587wag5DMxGXb8mMBaMluLNRoEVuPGbe04BlYQKKgCvR9Qx25qmTsdTVAxuz-BTp3mQ

### don't work
POST http://localhost:9000/oauth2/token?grant_type=password
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

username=test&password=12345

###
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=read&state=1234

###
POST http://localhost:9000/oauth2/token?grant_type=authorization_code
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

code=yL5D0rupMvLkPfxrwMTEPwnKZ_awFKSmUw0c8Dt3Btt9tpQox8LWk3IKGGCoNHU0qf0pQjtffjsFOG8XpXsVJcnd6igZ5cebj-itkGQS9gET8hYtTWpzIzGMM4YSeB01


### authorization code with PKCE
GET http://localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=read&state=1234&code_challenge=YmRmMTkyODk4YjJhYmM4MWQyOGNlZWYxMWJmODExMTYyMWZjY2ZhMGNjMGJjZTZlMjAwMGZlMzdmODc0MjcwZQ==&code_challenge_method=S256

###
POST http://localhost:9000/oauth2/token?grant_type=authorization_code
Content-Type: application/x-www-form-urlencoded

client_id=messaging-client&code_verifier=YmRmMTkyODk4YjJhYmM4MWQyOGNlZWYxMWJmODExMTYyMWZjY2ZhMGNjMGJjZTZlMjAwMGZlMzdmODc0MjcwZQ==&code=56-cR6n9A4xOvC20isAHAS2_2c4JWw0YdXk3k3kIkNX_LJ07ZKYVC2mmFbXUpunptO0kT_xV0u-fUi6MAEV7pjyMTGL4FN-6lSXk5VtUkLIJTI6IGa1EeafmwMsKmJcjy

###
POST http://localhost:9000/oauth2/token?grant_type=refresh_token
Content-Type: application/x-www-form-urlencoded

refresh_token=anYZ-Pz0-vClzZl5rZIpCWcOqWEycuPv1y7Vc5M0CpF7npOFaniWFtSAtMdO9FjxWh5aWC69nVr7S53qXpOtSZBFjcp1qiIl5HwmaCCD7SyqMPzdML0FoX-hv6HCCop-

#############
POST http://localhost:9000/oauth2/introspect
Content-Type: application/x-www-form-urlencoded

token=eyJraWQiOiI5ZmQxNjhhNy1jY2ZhLTRlZGUtYWFmMS1kZmQ3OTQ4ZTMyNGQiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTYyODQzNzk1Mywic2NvcGUiOlsicmVhZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTYyODQ1NTk1MywiaWF0IjoxNjI4NDM3OTUzLCJqdGkiOiIxZGM5ODJlNS1hMDNhLTQ4NmQtYjIwMi1mNjA0Zjg2MzI0MWMifQ.S7t2gT91_ikG3fbolwP0a9bZ-NlZpXxodRgmgWJk5HQMD22z2ZtvjSBkxeDQJVT6dWJyeEwK3AMk0v2zS7ahuVwfMa5r4__kGxCGbuBGUH13bv9_G8buNquS7sF-71fHivgTkrbIHpbdSVBwOiGY_vE0AcO3p442XONA_9jb_PoQcreo690LCh8q3JXXWWFgzdyscGAqBYPtyVTO-kicdxR95gKmaWYv953xoQTktOfZuH4pUyfRIeEeb5Baysr91qdR0TPZPoxU1IPyES-j1MG_pJjF0FalWqBIyrx2B1lx04Izaf9uiwicDOBwablIDyfKGlkTmEaNY--ghKjLdQ
