###
GET http://localhost:9000/oauth2/.well-known/jwks.json

###
GET http://localhost:9000/api/hello
Authorization: Bearer eyJraWQiOiIyMWNlNjYxYi0yNDJkLTQzNzYtYjYwZC1kOWFmZjJlY2M0OWQiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTYyODMzOTY5NCwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo5MDAwIiwiZXhwIjoxNjI4MzU3Njk0LCJpYXQiOjE2MjgzMzk2OTQsImp0aSI6IjI5YWM4YmM2LWQ5ZDQtNDRjNC1iOTEyLTkyMzNlOGJlZTZjZSJ9.W044UxSLRAsxEg_MCJeggIoLpjHK3lrKfLCzW01Ynx-wRrMKqk0ZBunX2ciT0fd0kCisfvEINUckk0kIAXfuCxJIAd_AYyR5pZKNadFICh-WfCZPmUUsB6ukrvFtDGbWiq_eiW-fHoO-ZJcITLXSNib_QgRhpeDkbSjwaS6Tiiuwii05u034jEkG4Y4dBaYH2mkoF5Udm3zhRQTuWHyDEEcl7mVvVPZEYOsAePWr8pJk11PoHQR3NrEXvQjoD3dpyY0jJPUpaOo8UxmNUeRvIaaDvoQuiGId_kaFLncjHExBcpWBLVi9bnDEenvVUtEslm3op47NnimEpxVtOOnnaw

###
POST http://localhost:9000/oauth2/token?grant_type=client_credentials
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

###
POST http://localhost:9000/oauth2/introspect?token=eyJraWQiOiIyM2I4YzU0NC1iMTY5LTRjMmEtYjU2Ni05YjMwYzEwMTg5N2UiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXNzYWdpbmctY2xpZW50IiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTYyODMyMzgwMCwic2NvcGUiOlsibWVzc2FnZTpyZWFkIiwibWVzc2FnZTp3cml0ZSJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTYyODMyNDEwMCwiaWF0IjoxNjI4MzIzODAwLCJqdGkiOiI4Mjk0Y2VlMS1hY2IwLTQzMWItOGEzOS1hMDM1YWM5MWVjYjkifQ.shRPjoKQ5PsYbSzueB_cDjaFYoAP0niMsZfnnwp20Op_CdsdfoFMEr49KF_3FfSBbvACO74zCRKNxCcJDP1ohv7rpwRm7-zfpn2IsEQIfhptLOxIlY8WvmzxbU0XWwnDJhEtdeU2EU32vdnxVB51RFFj18i0F5gBlI2FdFMIX7U_lYOHczzcYCEK8icG5zDhpel0SrNKq9fAwIEjksjSV6lH32dY_6XjbYDr8cCdf43wdlYPJhLEnbReTKMakIXzn9jigkGz4GbvyiXzMu8YW_Ob8cW5mzMktr9iH6ryi-Yd6uhU_u9P4X8IG2upuk6XUYpdiQouURf0tE-o2bJUhA
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

###
POST http://localhost:9000/oauth2/token?grant_type=password
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=
Content-Type: application/x-www-form-urlencoded

username=test&password=12345

###
GET http://localhost:9000/oauth2/authorize?grant_type=authorization_code&response_type=code&client_id=messaging-client&scope=read&state=1234

###
POST http://localhost:9000/oauth2/token?grant_type=authorization_code&code=6YjscNBvXrJ77z1mrUIya-Ch4cqMC8Y-1Avvi2E6doa5_BcMrl6lYPuso-Vfb8VK6ftI1fyu8uZf4x_4bpyK6_G5J0kNTSDRE7VAYuwopsf642pGOKaZxMTrU3TIQuB4
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

###
POST http://localhost:9000/oauth2/token?grant_type=refresh_token&refresh_token=6j1SvC3hNHDaArLLILKo3dFUGW3g41SNEwFY2mXYlRNOv7PcKK_ftq1NxZETez25zy0uOaF0oT6T5djj9aVr9faGFV43-o8Q3yYf_gyg1cgXpj3TFwLmVkm-Z0-hnGtl


