###
POST http://localhost:8080/oauth/token?grant_type=password
Authorization: Basic Y2xpZW50OnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

username=user&password=user

### password grant
POST http://localhost:8080/oauth/token?grant_type=password
Authorization: Basic Y2xpZW50OnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### client credentials grant
POST http://localhost:8080/oauth/token?grant_type=client_credentials
Authorization: Basic Y2xpZW50OnNlY3JldA==

### authorization code grant
GET http://localhost:8080/oauth/authorize?response_type=code&client_id=client&scope=read&state=12345

###
POST http://localhost:8080/oauth/token?grant_type=authorization_code&code=6Q04Nq
Authorization: Basic Y2xpZW50OnNlY3JldA==

### doesn't work
POST http://localhost:8080/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwib3JnYW5pemF0aW9uIjoidXNlcnJhbmRvbUFscGhhYmV0aWMoNCkiLCJhdGkiOiJraUFqTGo5NERSZG1tUnFnYjZ6cEJGZWhuTGsiLCJleHAiOjE2Mjg2NzAyMTQsImF1dGhvcml0aWVzIjpbInJlYWQiXSwianRpIjoiY2dTT0FLRHAwM2NCRThmck0wS0I1ZTJybVBZIiwiY2xpZW50X2lkIjoiY2xpZW50In0.g2Lb-VkJ5CgTSd_XKUaGS-s_EuHJly1FO33wXB5Ex9Gu4htaT-lWr7Ba9ddB5Upw7azc9r5WFo6kgyQqlUEixoU7qrHtAO8e1TkPdLrhXT1JGZcpcNdCrQ9ycq3zJ2x7qq17vcV6LQyI7WXABG4fNS_h_Q-0GMFqLP-ZMTHEisV9UfSkGvX7qF_TfYLcL8cvpRz8fTtLyt50Q0wzjiEHezdkV1zTTvDiudIShYfWHJgcV3sv_FPPaExx51sSDQpZX4cjT_BI2agDKyn_X4yqStu2FpNsZqxN24JBoQu-Up6d34PhJ3H-fOhPTwtEk1pdnzN1qaV37uL0Nm0yGfHWFg

###
GET http://localhost:8080/oauth/token_key

###
POST http://localhost:8080/oauth/check_token?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwib3JnYW5pemF0aW9uIjoidXNlcnJhbmRvbUFscGhhYmV0aWMoNCkiLCJleHAiOjE2Mjg0NzYwOTQsImF1dGhvcml0aWVzIjpbInJlYWQiXSwianRpIjoiVVVYQnRkM0l0eDhjUldLd0VTVGE4Uk1NalpvIiwiY2xpZW50X2lkIjoiY2xpZW50In0.G8UdlCCITs-UAEg31a2xcxFhGHpaFsF3HSVb-ChBlKna34pL8cAyjHsz8_0Ds3DlyI4ktwcuEVDihIw4D52hmunk5UQWIyeABnIdt0mDKJn5IYqnxtzKvfVSVtgl19aJAkSjMnpE1fzYEssz-JikcrYFjRvikMX3jk6v08uAwmK7b7O0n6tB9cqfENzDLBSRGApBOT6KnGasVLtu68p_bQgUbHdiqDEHTbui3A2l9iu11qJtUkC_ygOJJ9Gzc0hIls8U0qq0Pc7Ad-hR2waCcYDFlAeXPwguNJDWPtk3cmuvf6rgWBg5PLTa2GWDG6qas0ewjz9JyW8S3URu_RHEww

###
GET http://localhost:8080/api/hello
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXBpIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwib3JnYW5pemF0aW9uIjoidXNlcnJhbmRvbUFscGhhYmV0aWMoNCkiLCJleHAiOjE2Mjg0NzY4NzIsImF1dGhvcml0aWVzIjpbInJlYWQiXSwianRpIjoiMGdMYlZWRmZ6YUEyaWJMb2tjYzZ6S2wzY3ZZIiwiY2xpZW50X2lkIjoiY2xpZW50In0.MIK4zVeNNLlhb3Sg-lH8GKXWmcY80iJ9V_PcVYCJRni4p-zmvTltOlTnhCDL5I1SwNeZNT7eoR2fvHXtDxu5MV6SRVImN_EKEJMHbyKvvkgu7IZl3FnshlUyt86mPEwP7piLKeCPGZoKDEnWQEHJWUGYYU0wxRH5jEKww90ccFy0NJzHkVoPpSlO3uNPD0uhej65ZrlQEwKlZdMYX6o_KrLj77unyzg679WhlZzMIY5SeHqIpmYX4at-LomHHGIZfmR4nbVSLLxYFVLjw4HJJ_eAKk_-Tw-62Gsrcng5M40q9-aSIVqfgI9k_1N53RXUcAMNhow__8iMTRFF8l7bHw
