###
POST http://localhost:8080/oauth/token?grant_type=password
Authorization: Basic Y2xpZW50OnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

username=user&password=user

### password grant
POST http://localhost:8080/oauth/token?grant_type=password
Authorization: Basic Y2xpZW50OnNlY3JldA==
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### client credentials grant
POST http://localhost:8080/oauth/token?grant_type=client_credentials
Authorization: Basic Y2xpZW50OnNlY3JldA==

### authorization code grant
GET http://localhost:8080/oauth/authorize?response_type=code&client_id=client&scope=read&state=12345

###
POST http://localhost:8080/oauth/token?grant_type=authorization_code&code=6Q04Nq
Authorization: Basic Y2xpZW50OnNlY3JldA==


### doesn't work
POST http://localhost:8080/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbiIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJhdGkiOiJlZ3VNejROXzFEc2VGX1AwN2NjLVF2aHZyMGsiLCJleHAiOjE2MzA5ODgwOTcsImF1dGhvcml0aWVzIjpbIndyaXRlIiwicmVhZCJdLCJqdGkiOiJPYnlxNWdjWmJRMGZOWC03cFQ1cmtCMEdWWTAiLCJjbGllbnRfaWQiOiJjbGllbnQifQ.niSVIWdCpVd3r0Tms9uDcRcQuZTSo4-gkQQhx_BuUGUZpt8MyF_0F8M3aZmrC-96zUgQEvbvEGGZN2VB0Y68rZ2DxJf6i3cg0J1DqEpaY5DgE7cVGsTiwzXB0ZexFFlIsiRc1p0y2MsAo8Uq0S-zkM6CDFD99BqPtP1Rot45m8L85AupXbx2vmKtYkwhAWq-ZG1jpjyXCsMbbpZF4bdMIQxLMN4oqGG1zOaGLMg6PA9HIms5dGppm7ChVakRmffz-DLS7pJgq_cX3PB1iRRoOwjAGrU62nXmFSgP2IC5-8GEbpVcrE50Oc5gdkYPe4-ifP3iq4CWPSgauyrig2UxsQ

###
GET http://localhost:8080/oauth/token_key

###
POST http://localhost:8080/oauth/check_token?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjg0MzkzNjgsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsid3JpdGUiLCJyZWFkIl0sImp0aSI6Il96WXFGV3V5aGNUVENyZW9iQm9Xd2tMdjVIMCIsImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.wYmMLds1c6cqzzg-vkpyDw6o53Ghd0RrlCpg35Khq6ZfIoebxsej9d2hVBlkndP-KRlTlPS_GYeYtrxWk1eb6ntGltwwlAfym2YdxfDKeOyi_KPsbKIhXftX8fOfZvzYI-uIzLKGghOpOGWEMnSsxro9fOME1EHhX8Dfj_CgL_AUULJL_H7hcZAbMRBtlfNlkvBRNgTbqJCYKu_V51rAHZ0MCjdgIHX5tdaGfPxDe_3kCt4NjheESoe5j4OuJHk3HOZDY7_sO3y8lfXYzkD5lpL_F0FbE8e4Nn6D0-uyz_DvRmAZTso_rpuOxFOt37J4l7JGBcd6suC1ietdc13SOw
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ1c2VyIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sIm9yZ2FuaXphdGlvbiI6InVzZXJyYW5kb21BbHBoYWJldGljKDQpIiwiZXhwIjoxNjI4NDY4MzAxLCJhdXRob3JpdGllcyI6WyJyZWFkIl0sImp0aSI6IjVxdTZxNWhiX1lZb1lGb2tkY0x0dXo2MWpVZyIsImNsaWVudF9pZCI6ImNsaWVudCJ9.E5f2p8UlROau0Ih5OrW4uH4jO6i2R7rUFEncYgh5_aZCMrEntSizUbgPeqHezozSvkVGWePVp2Q8kz9E-t7d_5ut2VnHfMlvCfnuiOix8m5H6y0noGxchEQA-8pT2k4VpbOlNs97pwwDPX9nxKVGiWa8wbBXWeyVGi45n42XYjerql3IEVSAh5yJfMXJVTdN7fowx34dCrCUpbVCXmD85JkpKeCwq3KTf-CyN5gf9tC70m1vfZeKhW3Yx3_GROqpzdboAwmly8ehxCFvgiECPg_Lh3tLhHTzXKaFpzNOE5lCWXZjlPftOb89-cvbhJqFB9yivVbeGQI9ZdavPRdGGA

###
GET http://localhost:8080/api/hello
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsib2F1dGgyLXJlc291cmNlIl0sInVzZXJfbmFtZSI6InVzZXIiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwib3JnYW5pemF0aW9uIjoidXNlcnJhbmRvbUFscGhhYmV0aWMoNCkiLCJleHAiOjE2Mjg0MzAyMTQsImF1dGhvcml0aWVzIjpbInJlYWQiXSwianRpIjoielVOY1JZLXNHcjFRZmRRdk1icVlaZVh3cVNJIiwiY2xpZW50X2lkIjoiY2xpZW50In0.BCs51K96JNrV5FLQ1U7QSV-4I3bRAFNPDnW_ghPqBWz7Av4AUWvS4jPkkqh5uFbbInQKbxpjRNmNajnA6FU6niMUsqngk7jP787teVbAH_QdnWUjmihiwO5WdX9eeIXL0QIZ5FMxnP77xwe8B9OsZMO41fOJZquQUYJbA_wlx0AhzbZemLcpBs0v8A4oVvGaQhJFON6nqd3s9uVJZDxoEyO8RVrE0E7cIKtjpjtPuP7FtKcL_QGt5q5ris2OlvG-HNB__nfJg_49nlSVQFur-NotIyqEOShUwbkTOkiHqxeSaBSE9lhezTEkYL-VKHPCAgO6jc2sX1RRxb_wL4Yj2Q